bot:
  name: "policlinica"
  token: 6598381852:AAEzH2NcFBGZJ1Dkg7dKbPM3jawMBU-tBTk

spring:
  datasource:
    url: jdbc:postgresql://localhost:5414/policlinica
    username: postgress
    password: postgresspass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true