version: '3.8'
services:
  postgres:
    image: postgres:15.2
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgresspass
      POSTGRES_DB: policlinica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: